export const volunteerTypes = [
  { value: "animal_welfare", label: "Animal Welfare" },
  { value: "homeless", label: "Homelessness & Housing" },
  { value: "education", label: "Education & Literacy" },
  { value: "environment", label: "Environment & Conservation" },
  { value: "health", label: "Health & Medicine" },
  { value: "seniors", label: "Senior Support" },
  { value: "youth", label: "Youth Mentoring" },
  { value: "arts", label: "Arts & Culture" },
  { value: "disability_support", label: "Disability Support" },
  { value: "disaster_relief", label: "Disaster Relief" },
  { value: "technology", label: "Technology & Digital Literacy" },
  { value: "women_empowerment", label: "Women Empowerment" },
  { value: "refugees", label: "Refugee & Immigrant Support" },
  { value: "sports", label: "Sports & Recreation" },
  { value: "mental_health", label: "Mental Health" },
  { value: "community_development", label: "Community Development" },
];

export const locations = [
  { value: "sydney_nsw", label: "Sydney, New South Wales" },
  { value: "melbourne_vic", label: "Melbourne, Victoria" },
  { value: "brisbane_qld", label: "Brisbane, Queensland" },
  { value: "perth_wa", label: "Perth, Western Australia" },
  { value: "adelaide_sa", label: "Adelaide, South Australia" },
  { value: "hobart_tas", label: "Hobart, Tasmania" },
  { value: "darwin_nt", label: "Darwin, Northern Territory" },
  { value: "canberra_act", label: "Canberra, Australian Capital Territory" },
];

export const organizationTypes = [
  { value: "ngo", label: "Non-Governmental Organization (NGO)" },
  { value: "nonprofit", label: "Nonprofit Organization" },
  { value: "community_group", label: "Community Group" },
  { value: "social_enterprise", label: "Social Enterprise" },
  { value: "charity", label: "Charity" },
  { value: "educational_institution", label: "Educational Institution" },
  { value: "healthcare_provider", label: "Healthcare Provider" },
  { value: "religious_institution", label: "Religious Institution" },
  { value: "environmental_group", label: "Environmental Organization" },
  { value: "youth_organization", label: "Youth Organization" },
  { value: "arts_culture_group", label: "Arts & Culture Organization" },
  { value: "disaster_relief_agency", label: "Disaster Relief Agency" },
  { value: "advocacy_group", label: "Advocacy Group" },
  { value: "international_aid", label: "International Aid Organization" },
  { value: "sports_club", label: "Sports & Recreation Club" },
  { value: "animal_shelter", label: "Animal Shelter / Welfare Org" },
];
