export const suburbs = [
  { value: "sydney_cbd", label: "Sydney CBD", postcodes: ["2000", "2001"] },
  { value: "north_sydney", label: "North Sydney", postcodes: ["2060", "2059"] },
  { value: "bondi", label: "Bondi", postcodes: ["2026", "2024"] },
  { value: "manly", label: "Manly", postcodes: ["2095"] },
  {
    value: "parramatta",
    label: "Parramatta",
    postcodes: ["2150", "2124", "2151"],
  },
  { value: "newtown", label: "Newtown", postcodes: ["2042"] },
  { value: "chatswood", label: "Chatswood", postcodes: ["2067", "2057"] },
  { value: "cronulla", label: "Cronulla", postcodes: ["2230"] },
  { value: "darlinghurst", label: "Darlinghurst", postcodes: ["2010"] },
  { value: "balmain", label: "Balmain", postcodes: ["2041"] },
  { value: "surry_hills", label: "Surry Hills", postcodes: ["2010"] },
  { value: "paddington", label: "Paddington", postcodes: ["2021"] },
  { value: "bondi_junction", label: "Bondi Junction", postcodes: ["2022"] },
  { value: "coogee", label: "Coogee", postcodes: ["2034"] },
  { value: "maroubra", label: "Maroubra", postcodes: ["2035"] },
  { value: "randwick", label: "Randwick", postcodes: ["2031"] },
  { value: "kensington", label: "Kensington", postcodes: ["2033"] },
  { value: "kingsford", label: "Kingsford", postcodes: ["2032"] },
  { value: "rosebery", label: "Rosebery", postcodes: ["2018"] },
  { value: "zetland", label: "Zetland", postcodes: ["2017"] },
 ];
